-- O Supabase expõe o schema public pela API de dados (chave anon).
-- Com RLS ligado e sem políticas, só o dono das tabelas (usado pela API) acessa.
ALTER TABLE "Household" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecurringBill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Bill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditCard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CardPurchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CardInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Income" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reserve" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReserveMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShoppingItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
